create CardAccount model
IT-Academy-Kyrgyzstan/cs2001-ewallet pull request #13
Opened 2021-01-25 19:16 UTC by Doranbek

Closed #8

2021-01-26 05:26 UTC, kebyavonatlus commented on DataAccess/CardAccount.cs
> +        public enum Statuses
думаю энамы лучше поместить в отдельную папку

2021-01-26 05:48 UTC, kebyavonatlus requested changes
энам переметсить в отдельную директорию, удалить лишние комменты, скорее всего нужно вернуть UserId

2021-01-26 05:48 UTC, kebyavonatlus commented on DataAccess/CardAccount.cs
> +        [Column(TypeName = "DateTime.Now")]
Здесь указывается только тип, но тут вызывается метод. Будет ошибка при компиляции

2021-01-26 05:48 UTC, kebyavonatlus commented on DataAccess/CardAccount.cs
> +        [Column(TypeName = "numeric")]
для numeric нужно указать количество цифр до запятой и после. По умолчанию будет (18.0)

2021-01-27 13:47 UTC, amankkg requested changes

2021-01-27 13:47 UTC, amankkg commented on CardAccount.sql
> +	UserId int NULL,
`NOT NULL`

2021-01-27 13:47 UTC, amankkg commented on DataAccess/CardAccount.cs
> +        [Display(Name = "Номер Карты")]
Удалить эти атрибуты из проекта доступа к данным

2021-01-28 06:32 UTC, rustam217 commented on SQLSCRIPT.sql
> +	BardBalance Numeric(12,2) NULL,
BardBalance или там CardBalace ?

2021-01-28 07:09 UTC, kebyavonatlus requested changes
Есть опечатки

2021-01-28 07:09 UTC, kebyavonatlus commented on DataAccess/User.cs
> +        public string Created { get; set; }
Здесь в скрипте создания бд указывается тип Date

2021-02-02 12:07 UTC, kebyavonatlus approved these changes
Вроде бы все ок

2021-02-03 13:14 UTC, amankkg approved these changes

2021-02-03 13:14 UTC, merged