add Card issuance application form
IT-Academy-Kyrgyzstan/cs2001-ewallet pull request #55
Opened 2021-03-03 20:23 UTC by Doranbek

Close #51

2021-03-04 03:49 UTC, kebyavonatlus requested changes

2021-03-04 03:49 UTC, kebyavonatlus commented on DataAccess/CardApplication.cs
> +        public int CurruncyEnum { get; set; }
здесь нужно использовать тип enum которую вы создали

2021-03-04 03:49 UTC, kebyavonatlus commented on DataAccess/CardApplication.cs
> +        public int CardView { get; set; }
здесь так же нужно указать enum

2021-03-04 03:49 UTC, kebyavonatlus commented on DataAccess/CardApplication.cs
> +        [ForeignKey("UserId")]
атрибут foreign key вроде же не нужен, мы же создаем файл sql или для чего он?

2021-03-04 03:49 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +                var userLogin = User.Identity.Name;
контроллер Home уже наследует базовый контроллер BaseController и там уже есть userId лучше использовать его

2021-03-04 03:49 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +                    Status = 2,
при присвоении статуса лучше использовать сам enum таким образом StatusesEnum.Considering

2021-03-04 03:49 UTC, kebyavonatlus commented on DataAccess/CardApplication.cs
> +        public int Status { get; set; }
здесь так же нужно использовать enum

2021-03-04 03:49 UTC, kebyavonatlus commented on DataAccess/CardApplication.cs
> +    public class CardApplication
нужно указать атрибут Required для обязательных полей

2021-03-04 03:49 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +        public async Task<IActionResult> FormApp(FormAppViewModels model)
не нашел модельку FormAppViewModels

2021-03-04 03:49 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +                await db.SaveChangesAsync();
при успехе наверное что-то надо вернуть пользователю или же редирект

2021-03-04 15:07 UTC, kebyavonatlus requested changes

2021-03-04 15:07 UTC, kebyavonatlus commented on Web/Views/Home/FormApp.cshtml
> +                <input asp-for="Curruncy" placeholder="Сurruncy" />
здесь не input а select

2021-03-04 15:07 UTC, kebyavonatlus commented on Web/Views/Home/FormApp.cshtml
> +                <input asp-for="CardView" placeholder="CardView" />
Здесь тоже нужнен select

2021-03-04 15:07 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +                return View(model);
При ошибке так же нужно указать причину и отобразить ошибку во вью. Можете использовать ValidationSummary или же передать через ViewBag

2021-03-04 15:07 UTC, kebyavonatlus commented on Web/Models/FormAppViewModels.cs
> +    public class FormAppViewModels
нужен атрибут required

2021-03-05 13:55 UTC, amankkg requested changes

2021-03-05 13:55 UTC, amankkg commented on DataAccess/Enum/CurrunsesEnum.cs
> +    public enum CurruncyEnum
```suggestion
    public enum Currency
```

2021-03-05 13:55 UTC, amankkg commented on DataAccess/Enum/CardViewsEnum.cs
> +    public enum CardViewsEnum
```suggestion
    public enum CardType
```

2021-03-05 13:55 UTC, amankkg commented on DataAccess/CardApplication.cs
> +        public StatusesEnum Status { get; set; }
```suggestion
        public CardStatus Status { get; set; }
```

2021-03-05 13:55 UTC, amankkg commented on Web/Controllers/HomeController.cs
> +                var nameCard = $"{user.FirstName} + {user.LastName} + {model.CardView}";
в интерполяции строк конкатенация не нужна

2021-03-05 13:55 UTC, amankkg commented on Web/Controllers/HomeController.cs
> +                var nameCard = $"{user.FirstName} + {user.LastName} + {model.CardView}";
кажется эта переменная не нужна пока

2021-03-08 10:24 UTC, kebyavonatlus commented
Были созданы энамы CardStatus, CardType, Currency но остались старые файлы которые нужно удалть с проекта  CardViewsEnum, CurrunsesEnum, StatusesEnum

2021-03-08 10:28 UTC, kebyavonatlus commented
Так же был сменен экшн с FromApp на CardAppForm которые тоже вроде бы лишние в проекте

2021-03-08 11:08 UTC, kebyavonatlus requested changes

2021-03-08 11:08 UTC, kebyavonatlus commented on Web/Views/Home/CardAppForm.cshtml
> +                <button>Send</button>
Наверное нужно переименовать кнопку на создать заявку или отправить заявку

2021-03-08 11:08 UTC, kebyavonatlus commented on Web/Controllers/HomeController.cs
> +                await db.SaveChangesAsync();
При успехе есть редирект но нет сообщения об успешном создании заявки

2021-03-10 13:34 UTC, amankkg commented on DataAccess/CardApplication.cs
> +        public DateTime DecisionDate { get; set; }
```suggestion
        public DateTime? DecisionDate { get; set; }    
```

2021-03-10 13:49 UTC, amankkg approved these changes

2021-03-10 13:50 UTC, kebyavonatlus approved these changes

2021-03-10 13:51 UTC, merged